'use client';

import { useState } from 'react';
import { marked } from 'marked';
import {
  ResponsiveContainer, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell,
  XAxis, YAxis, Tooltip, CartesianGrid,
} from 'recharts';
import { Sparkles, Play, Database, FileDown } from 'lucide-react';

type Preset = { key: string; label: string; audience: string; prompt: string };
type Chart = { type: 'bar' | 'line' | 'pie'; xKey: string; series: string[]; data: Record<string, unknown>[]; title?: string };
type Table = { columns: string[]; rows: (string | number | null)[][]; caption?: string };
type Section = { heading: string; body: string; table?: Table; chart?: Chart; cites?: number[] };
type Report = { title: string; audience: string; tldr: string[]; kpis: { label: string; value: string; note?: string }[]; sections: Section[]; methodology: string };
type QueryTrace = { i: number; sql: string; rowCount: number; error?: string };
type Result = { report: Report; queries: QueryTrace[]; model: string; costUsd: number };

const COLORS = ['#38bdf8', '#a78bfa', '#34d399', '#fbbf24', '#f87171', '#f472b6'];
const AUD = [
  { key: 'clevel', label: 'C-level' },
  { key: 'analyst', label: 'Analyst' },
  { key: 'content', label: 'Content / PR' },
];

function ChartView({ c }: { c: Chart }) {
  if (c.type === 'pie') {
    const k = c.series[0] ?? 'value';
    return (
      <ResponsiveContainer width="100%" height={260}>
        <PieChart>
          <Pie data={c.data} dataKey={k} nameKey={c.xKey} outerRadius={95} label>
            {c.data.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
          </Pie>
          <Tooltip contentStyle={{ background: '#16203c', border: '1px solid #1e2a4a', borderRadius: 8, fontSize: 12 }} />
        </PieChart>
      </ResponsiveContainer>
    );
  }
  const Ch = c.type === 'line' ? LineChart : BarChart;
  return (
    <ResponsiveContainer width="100%" height={280}>
      <Ch data={c.data} margin={{ top: 8, right: 12, bottom: 4, left: -8 }}>
        <CartesianGrid stroke="#1e2a4a" vertical={false} />
        <XAxis dataKey={c.xKey} tick={{ fill: '#7c8cab', fontSize: 11 }} tickLine={false} />
        <YAxis tick={{ fill: '#7c8cab', fontSize: 11 }} tickLine={false} width={40} />
        <Tooltip contentStyle={{ background: '#16203c', border: '1px solid #1e2a4a', borderRadius: 8, fontSize: 12 }} />
        {c.series.map((s, i) => c.type === 'line'
          ? <Line key={s} type="monotone" dataKey={s} stroke={COLORS[i % COLORS.length]} strokeWidth={2} dot={false} />
          : <Bar key={s} dataKey={s} fill={COLORS[i % COLORS.length]} radius={[3, 3, 0, 0]} />)}
      </Ch>
    </ResponsiveContainer>
  );
}

function ReportView({ r }: { r: Result }) {
  const rep = r.report;
  return (
    <div className="flex flex-col gap-4">
      <div>
        <h2 className="text-xl font-bold text-slate-100">{rep.title}</h2>
        <p className="mt-1 text-xs text-slate-500">
          Audience: <span className="text-slate-400">{rep.audience}</span> · generated by <span className="text-slate-400">{r.model}</span> · ${r.costUsd.toFixed(3)} · {r.queries.length} queries run
        </p>
      </div>

      {rep.tldr?.length > 0 && (
        <div className="rounded-lg border border-sky-500/25 bg-sky-500/[0.05] px-4 py-3">
          <p className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-sky-300">Bottom line</p>
          <ul className="flex flex-col gap-1 text-sm text-slate-200">
            {rep.tldr.map((t, i) => <li key={i} className="flex gap-2"><span className="text-sky-400">•</span>{t}</li>)}
          </ul>
        </div>
      )}

      {rep.kpis?.length > 0 && (
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {rep.kpis.map((k, i) => (
            <div key={i} className="rounded-lg border border-[var(--border)] bg-white/[0.02] px-3 py-2.5">
              <p className="text-[10px] uppercase tracking-wide text-slate-500">{k.label}</p>
              <p className="mt-0.5 text-xl font-bold text-slate-100">{k.value}</p>
              {k.note && <p className="text-[11px] text-slate-500">{k.note}</p>}
            </div>
          ))}
        </div>
      )}

      {rep.sections?.map((s, i) => (
        <section key={i} className="panel px-5 py-4">
          <h3 className="mb-2 text-sm font-semibold text-slate-200">{s.heading}</h3>
          <div className="prose-invert max-w-none text-sm leading-relaxed text-slate-300 [&_a]:text-sky-400 [&_li]:my-0.5 [&_strong]:text-slate-100 [&_ul]:my-2 [&_ul]:list-disc [&_ul]:pl-5"
            dangerouslySetInnerHTML={{ __html: marked.parse(s.body || '', { async: false }) as string }} />
          {s.chart && s.chart.data?.length > 0 && (
            <div className="mt-3">
              {s.chart.title && <p className="mb-1 text-xs font-medium text-slate-400">{s.chart.title}</p>}
              <ChartView c={s.chart} />
            </div>
          )}
          {s.table && s.table.rows?.length > 0 && (
            <div className="mt-3 overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead><tr className="border-b border-[var(--border)] text-slate-500">
                  {s.table.columns.map((c) => <th key={c} className="px-2 py-1.5 font-medium">{c}</th>)}
                </tr></thead>
                <tbody>
                  {s.table.rows.map((row, ri) => (
                    <tr key={ri} className="border-b border-[var(--border)]/50">
                      {row.map((cell, ci) => <td key={ci} className="px-2 py-1.5 text-slate-300">{cell === null ? '—' : String(cell)}</td>)}
                    </tr>
                  ))}
                </tbody>
              </table>
              {s.table.caption && <p className="mt-1 text-[11px] text-slate-600">{s.table.caption}</p>}
            </div>
          )}
          {s.cites && s.cites.length > 0 && (
            <p className="mt-2 text-[11px] text-slate-600">Sources: {s.cites.map((c) => `SQL #${c}`).join(', ')}</p>
          )}
        </section>
      ))}

      {rep.methodology && (
        <p className="text-[11px] leading-relaxed text-slate-500"><span className="font-semibold text-slate-400">Methodology:</span> {rep.methodology}</p>
      )}

      {/* Provenance appendix — every number traces to one of these queries */}
      <details className="rounded-lg border border-[var(--border)] bg-white/[0.02] px-4 py-3">
        <summary className="cursor-pointer text-xs font-semibold text-slate-400"><Database className="mr-1 inline size-3.5" /> Data provenance — {r.queries.length} queries against your project’s data</summary>
        <div className="mt-2 flex flex-col gap-2">
          {r.queries.map((q) => (
            <div key={q.i} className="text-[11px]">
              <span className="text-slate-500">#{q.i} · {q.error ? <span className="text-red-400">error</span> : `${q.rowCount} rows`}</span>
              <pre className="mt-0.5 overflow-x-auto rounded bg-black/40 p-2 text-[11px] text-slate-400">{q.sql}</pre>
            </div>
          ))}
        </div>
      </details>
    </div>
  );
}

export function DataScientist({ presets }: { presets: Preset[] }) {
  const [audience, setAudience] = useState('analyst');
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState<Result | null>(null);

  const run = async (q: string, aud: string) => {
    if (!q.trim() || loading) return;
    setLoading(true); setError(''); setResult(null);
    try {
      const res = await fetch('/api/analyst', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question: q, audience: aud }),
      });
      const data = await res.json();
      if (!res.ok) setError(data.error || 'Analysis failed.');
      else setResult(data as Result);
    } catch (e) {
      setError((e as Error).message);
    } finally { setLoading(false); }
  };

  return (
    <div className="flex flex-col gap-4">
      <div className="panel px-5 py-4">
        <div className="mb-2 flex flex-wrap items-center gap-2">
          <span className="text-[11px] uppercase tracking-wide text-slate-600">Audience:</span>
          {AUD.map((a) => (
            <button key={a.key} onClick={() => setAudience(a.key)}
              className={`rounded-full border px-3 py-1 text-xs transition ${audience === a.key ? 'border-sky-400 bg-sky-500/15 text-slate-100' : 'border-[var(--border)] text-slate-400 hover:text-slate-200'}`}>
              {a.label}
            </button>
          ))}
        </div>
        <textarea value={question} onChange={(e) => setQuestion(e.target.value)} rows={3}
          placeholder="Ask for an analysis — e.g. “A competitor launched Tuesday. Did it hurt us? Give me a board memo.”"
          className="w-full resize-y rounded-lg border border-[var(--border)] bg-white/5 px-3 py-2 text-sm text-slate-100 outline-none focus:border-sky-500" />
        <div className="mt-2 flex flex-wrap items-center gap-2">
          <button onClick={() => run(question, audience)} disabled={loading || !question.trim()}
            className="inline-flex items-center gap-1.5 rounded-lg bg-sky-500 px-4 py-2 text-sm font-medium text-slate-950 hover:bg-sky-400 disabled:opacity-50">
            <Play className="size-3.5" />{loading ? 'Analyzing your data…' : 'Run analysis'}
          </button>
          {loading && <span className="text-xs text-slate-500">Querying, computing and writing — this can take 20-40s.</span>}
        </div>
        <div className="mt-3 flex flex-wrap gap-1.5 border-t border-[var(--border)] pt-3">
          <span className="mr-1 text-[11px] uppercase tracking-wide text-slate-600"><Sparkles className="mr-1 inline size-3" />Deep analyses:</span>
          {presets.map((p) => (
            <button key={p.key} onClick={() => { setQuestion(p.prompt); setAudience(p.audience); run(p.prompt, p.audience); }}
              disabled={loading}
              className="rounded-full border border-[var(--border)] px-2.5 py-1 text-xs text-slate-300 hover:bg-white/5 disabled:opacity-50">
              {p.label}
            </button>
          ))}
        </div>
      </div>

      {error && <p className="rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-2.5 text-sm text-red-300">{error}</p>}

      {result && (
        <>
          <div className="flex items-center justify-end">
            <button onClick={() => window.print()} className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-200">
              <FileDown className="size-3.5" /> Print / Save as PDF
            </button>
          </div>
          <ReportView r={result} />
        </>
      )}
    </div>
  );
}
