import { getCurrentUser, isAdmin } from '@/lib/auth';
import { getCurrentProject } from '@/lib/data';
import { PageHeader, EmptyState } from '@/components/ui';
import { ReportTabs } from '@/components/report-tabs';
import { ReportBuilder } from '@/components/report-builder';

export const metadata = { title: 'Custom report' };
export const dynamic = 'force-dynamic';

export default async function ReportPage() {
  if (!isAdmin(await getCurrentUser())) return <EmptyState message="Building reports is available to admins." />;
  const project = await getCurrentProject();
  if (!project) return <EmptyState message="Select a project first." />;

  return (
    <>
      <PageHeader
        title="Custom report"
        subtitle="Choose the charts you need, put them in the order you want, and add the commentary — written by you or generated by the AI from the project’s own numbers."
        info="A report here is an OUTLINE, not a frozen document: only the choice of charts, their order and your comments are stored. The figures are recomputed from the archive every time you export, so re-exporting the same report next month tells next month’s story. AI comments are written from figures already computed by SQL — the model interprets, it never produces a number. Every comment stays editable, and editing one marks it as yours. Every exported file carries the AI Act disclosure."
      />
      <ReportTabs />
      <ReportBuilder />
    </>
  );
}
